export const articlesContent = [
  {
    title: "Stuttgart",
    imageUrl: "./images/stuttgart.webp",
    imageAlt: "Image of a beautiful hill in Stuttgart Germany",
    iconUrl: "./images/heart.svg",
    likedIconUrl: "./images/heart-liked.svg",
    isLiked: false,
  },
  {
    title: "Berlin ",
    imageUrl: "./images/berlin.webp",
    imageAlt: "Image of the Berlin arches",
    iconUrl: "./images/heart.svg",
    likedIconUrl: "./images/heart-liked.svg",
    isLiked: false,
  },
  {
    title: " Nagoyan",
    imageUrl: "./images/nagoyan.webp",
    imageAlt: "Image of a cherry blosom near a temple in Nagoyan",
    iconUrl: "./images/heart.svg",
    likedIconUrl: "./images/heart-liked.svg",
    isLiked: false,
  },
  {
    title: "Japan",
    imageUrl: "./images/japan.webp",
    imageAlt: "Image of downtown Tokyo Japan",
    iconUrl: "./images/heart.svg",
    likedIconUrl: "./images/heart-liked.svg",
    isLiked: false,
  },
  {
    title: "Chichenitza",
    imageUrl: "./images/chichenitza.webp",
    imageAlt: "Image of main piramid at Chichenitza",
    iconUrl: "./images/heart.svg",
    likedIconUrl: "./images/heart-liked.svg",
    isLiked: false,
  },
  {
    title: "CDMX",
    imageUrl: "./images/cdmx.webp",
    imageAlt: "Image of Bellas Artes palace in downtown Mexico city",
    iconUrl: "./images/heart.svg",
    likedIconUrl: "./images/heart-liked.svg",
    isLiked: false,
  },
];

export const config = {
  placeDetails: {},
  cardsSectionSelector: "#articles",
  formSelector: ".popup__form",
  inputSelector: ".popup__input",
  submitButtonSelector: ".popup__button-submit",
  inactiveButtonState: "disabled",
  inputErrorClass: "popup__input_type_error",
  errorClass: "popup__error_visible",
  popupProfileSelector: "#edit-profile-popup",
  popupPlaceSelector: "#add-place-popup",
  popupImageSelector: "#popup__img-zoom",
  popupIsVisibleClass: "popup-active",
  popupIsHiddenClass: "popup_hidden",
  popupCloseButtonSelector: ".popup__button-close",
  editProfileBtnElement: document.querySelector("#edit-profile-btn"),
  profilePopupElement: document.querySelector("#edit-profile-popup"),
  profileForm: document.querySelector("#form-profile"),
  formDetailsCloseBtn: document.querySelector("#popup-button-close"),
  addNewPlaceBtn: document.querySelector(".nav__button-add"),
  addPlacePopup: document.querySelector("#add-place-popup"),
  addPlaceCloseBtn: document.querySelector("#popup-add-place-close"),
  addPlaceForm: document.querySelector("#form-place"),
  placeInputTitle: document.querySelector("#popup-input-title"),
  formInputSource: document.querySelector("#form-img-src"),
  formPlaceSubmitBtn: document.querySelector("#popup-button-place-submit"),
  articlesSection: document.querySelector("#articles"),
  imgPopup: document.querySelector("#popup__img-zoom"),
  imgPopupClose: document.querySelector("#popup-image-close"),
  imgZoom: document.querySelector("#zoom-img"),
  figCaption: document.querySelector(".popup__figcaption"),
  popups: document.querySelectorAll(".popup"),
};
